import Head from "next/head";
// import Link from "next/link";
import styles from "../styles/Home.module.css";

const Layout: React.FC = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Games Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <nav> </nav>
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Game Catalog</h1>
        <br />
        <p className={styles.description}>
          Bienvenue sur notre site de jeux vidéos !
          <code className={styles.code}></code>
        </p>
        <article>{children}</article>
        {/* <div>
          <button>
            <Link href="/actorsList">ActorsList</Link>
          </button>
          <p>{actorsList}</p>
        </div> */}
      </main>
      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Powered by{" Kevin"}
          <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
};

export default Layout;
