import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

const Layout: React.FC = ({ children }) => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Games Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <nav>
          <button>
            <Link href="/">Home</Link>
          </button>
          <button>
            <Link href="/games">Games</Link>
          </button>
          <button>
            <Link href="/platforms">Platforms</Link>
          </button>
        </nav>
      </Head>
      <main className={styles.main}>
        {/* <a href="/api/auth/login">Login</a>
        <a href="/api/auth/logout">Logout</a> */}
        <h1 className={styles.title}>Game Catalog</h1>
        <br />
        <p className={styles.description}>
          Bienvenue sur notre site de jeux vidéos !
          <code className={styles.code}></code>
        </p>
        <article>{children}</article>
        {/* <div>
          <button>
            <Link href="/NAMA">NAME</Link>
          </button>
          <p>{NAME}</p>
        </div> */}
      </main>
      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Powered by{" Kevin"}
          <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
};

export default Layout;
