import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";
import { useUser } from "@auth0/nextjs-auth0";

const Layout: React.FC = ({ children }) => {
  const { user, error, isLoading } = useUser();
  if (isLoading) return <div>Loading...</div>;
  if (error) return <div>{error.message}</div>;

  if (user) {
    return (
      <div className={styles.container}>
        <Head>
          <title>Games Catalog</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <nav>
          Welcome {user.name} !{" "}
          <button>
            <a href="/api/auth/logout"> Logout</a>
          </button>
          <button>
            <Link href="/">Home</Link>
          </button>
          <button>
            <Link href="/games">Games</Link>
          </button>
          <button>
            <Link href="/platforms">Platforms</Link>
          </button>
          <button>
            <Link href="/panier">Panier</Link>
          </button>
        </nav>
        <main className={styles.main}>
          <h1 className={styles.title}>Game Catalog</h1>
          <br />
          <p className={styles.description}>
            Bienvenue sur mon site de jeux vidéos !
            <code className={styles.code}></code>
          </p>
          <article>{children}</article>
        </main>
        <footer className={styles.footer}>
          <a target="_blank" rel="noopener noreferrer">
            Powered by{" Kevin"}
            <span className={styles.logo}></span>
          </a>
        </footer>
      </div>
    );
  }
  return (
    <div className={styles.container}>
      <Head>
        <title>Games Catalog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <nav>
        <button>
          <a href="/api/auth/login">Login</a>
        </button>
        <button>
          <Link href="/">Home</Link>
        </button>
        <button>
          <Link href="/games">Games</Link>
        </button>
        <button>
          <Link href="/platforms">Platforms</Link>
        </button>
      </nav>
      <main className={styles.main}>
        <h1 className={styles.title}>Game Catalog</h1>
        <br />
        <p className={styles.description}>
          Bienvenue sur mon site de jeux vidéos !
          <code className={styles.code}></code>
        </p>
        <article>{children}</article>
      </main>
      <footer className={styles.footer}>
        <a target="_blank" rel="noopener noreferrer">
          Powered by{" Kevin"}
          <span className={styles.logo}></span>
        </a>
      </footer>
    </div>
  );
};

export default Layout;
